# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Article.create(title: "Is there someone who can watch us?", author: "Matt Healy", body: "I used to have a reoccurring dream when I was younger. The narrative was loosely based, but the setting was always the surrounding areas of where my parents grew up. I think I was slightly obsessed with how certain, bleak areas of Northern England contained my history and the soul of my family, my psyche - I always felt connected and disconnected at the same time. Metaphorically and physically I would visit these places frequently as a youngster and in turn have used them as the setting to a lot of the stories in The 1975 - the North East was the visual setting to my formative years.")
Article.create(title: "Between the stripes", author: "Leonardo San Miguel", body: 'Pantomime lore dates as far back as the eight century BC, but it was never formalized as an artthe one we know now we know nowuntil around the sixteenth century in Easter Europe. Although almost every record of Pantomime implies the art was primarily conceived as a form of entertainment, there have always been traces that indicate the art was a manifestation of a grander concept: that of revelation through absence. Indeed, a pantomimes performance is, however comical or banal, a form of illusionism. As author Edward Lancaster writes in The Mysticism of Performing Arts, There is no greater demonstration of magic than that of creating entire worlds and realities through the use of nothing but ones body in motion and the unrelenting desire of the human mind to fill in the blanks.
')
Article.create(title: "Water", author: "Diana Storm", body: "Benjamin is laying on a field of grass and it is the middle of a windy, but warm day. He is staring at the sky. Blue looking at blue, but hidden under a pair of aviators. His hair cannot yet decide if it is a dark yellow or a light brown, and he likes that.")